### DISCUSSION TITLE
Data Science Notebook: Image Capability Matrix

### DISCUSSION THREAD

**Discussion by qcaas-nhs-sjt** [lsc-sde/lsc-sde#50] [Ideas]
Rather than having a single image, I wondered about whether we should be creating a base image and a matrix of capabilities such as:

| Component | Depends On |
| --- | --- |
| RStudio | - |
| Quarto | - |
| Code-Server | - |
| charliermarsh.ruff | Code-Server |
| davidanson.vscode-markdownlint | Code-Server |
| ms-python.black-formatter | Code-Server |
| ms-python.python | Code-Server |
| ms-pyright.pyright | Code-Server |
| njpwerner.autodocstring | Code-Server |
| quarto.quarto  | Code-Server, Quarto |
| VNC | - |
| XFCE | VNC |
| gnumeric | XFCE |
| abiword | XFCE |
 
We could then have a docker image for each variation of this matrix

Instead of selecting an image name, we then select the capabilities that we want to be available to the workspace, this in turn will convert this into an image name selecting the image with only the specific capabilities requested. This will lower security risks and reduce image size. If we then add items to the matrix this will in turn cause additional images to be built.

We can handle this via chaining the docker images using arguments for the base image:

```dockerfile
ARG BASE_IMAGE="lscsde/datascience-notebook-base"
FROM $BASE_IMAGE
```
The pipeline will then pass in the arg of the previous image.

So as an example if we want an image with the following capabilities:

* Code-Server
** ms-python.python
** ms-pyright.pyright
** quarto.quarto 
* Quarto

It will build as follows:
```mermaid
flowchart TB
  A[lscsde/datascience-notebook:1.0.0] --> B[lscsde/datascience-notebook:1.0.0-codeserver] --> C[lscsde/datascience-notebook:1.0.0-codeserver_python] --> D[lscsde/datascience-notebook:1.0.0-codeserver_python_pyright] --> E[lscsde/datascience-notebook:1.0.0-codeserver_python_pyright_quarto] --> F[lscsde/datascience-notebook:1.0.0-codeserver_python_pyright_quarto_quarto-ext]
  B --> Z[lscsde/datascience-notebook:1.0.0-codeserver_quarto]
  A --> Y[lscsde/datascience-notebook:1.0.0-quarto]
```

On the system the analyticsworkspace custom resource might look something like the following:
```yaml
apiVersion: xlscsde.nhs.uk/v1
kind: AnalyticsWorkspace
metadata:
  name: example-workspace
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  displayName: An example workspace
  description: |
    An example workspace
  
  validity:
    availableFrom: "2022-01-01"
    expires: "2030-01-01"
  
  jupyterWorkspace:
    imagePicker:
      capabilities:
      - code-server
      - ms-python.python
      - ms-pyright.pyright
      - quarto.quarto 
      - quarto
```

of course in reality we probably wouldn't use the full name of each component in the tag name, because this would create image names that are too long, so we would likely find some other methodolgy, to create the tag names that could be decoded by the analytics workspace manager
