### ISSUE TITLE
configure production workspaces

### ISSUE THREAD

**Issue by qcaas-nhs-sjt** [lsc-sde/lsc-sde#20]
As product owner we would like the following workspaces to be configured in the production environment of jupyter:

```yaml
workspaces:
    10_ws_advanced:
      display_name: Advanced Generic Workspace
      description: Advanced environment for testing with Python R and Julia.
      start_date: 2022-01-01
      end_date: 2030-01-01
      kubespawner_override: *jupyter_advanced
    vc-sd:
      display_name: VC-SD Workspace
      description: Shared workspace for VC and SD
      start_date: 2022-05-01
      end_date: 2025-12-31
      kubespawner_override: *jupyter_advanced
      storage:
        volumes:
          - name: landerhub-vc-sd
            persistentVolumeClaim:
              claimName: pvc-landerhub-vc-sd
        volume_mounts:
          - name: landerhub-vc-sd
            mountPath: /home/jovyan/landerhub-vc-sd
            readOnly: False

    lth-dst:
      display_name: LTH Data Science Team Workspace
      description: Shared workspace for LTH DST
      start_date: 2022-06-22
      end_date: 2025-12-31
      kubespawner_override: *jupyter_advanced
      storage:
        volumes:
          - name: landerhub-lth-dst
            persistentVolumeClaim:
              claimName: pvc-landerhub-lth-dst
        volume_mounts:
          - name: landerhub-lth-dst
            mountPath: /home/jovyan/landerhub-lth-dst
            readOnly: False
    

    mmu_dfu_cpu:
      display_name: Diabetic Foot Ulcer Research
      description: |
        Python environment with JupyterLab, Code and XCFE.
        Upto 8 vCPU and 32GB RAM. (No GPU)

        All work must be stored in /home/jovyan/dfu.
        Any work saved outside of this folder will be lost between sessions.
      start_date: 2023-07-06
      end_date: 2024-01-03
      kubespawner_override:
        image: crlander.azurecr.io/vvcb/cpu-dfu:2023-07-26
        defaultUrl: "/lab/tree/dfu"
        mem_guarantee: 4G
        mem_limit: 32G
        cpu_guarantee: 0.1
        cpu_limit: 8
      storage:
        volumes:
          - name: dfu
            persistentVolumeClaim:
              claimName: pvc-landerhub-dfu
        volume_mounts:
          - name: dfu
            mountPath: /home/jovyan/dfu
            readOnly: False

    avoidable_admissions:
      display_name: Avoidable Admissions
      description: Collaboration with Lancaster University on Avoidable Admissions
      start_date: 2023-09-01
      end_date: 2026-07-01
      kubespawner_override: *jupyter_advanced
      storage:
        volumes:
          - name: landerhub-avoidable-admissions
            persistentVolumeClaim:
              claimName: pvc-landerhub-avoidable-admissions
        volume_mounts:
          - name: landerhub-avoidable-admissions
            mountPath: /home/jovyan/landerhub-avoidable-admissions
            readOnly: False

```
